"""
Django settings for web_2025 project.
Generated by 'django-admin startproject' using Django 4.2.
"""

import os
from pathlib import Path
from django.core.management.utils import get_random_secret_key
from django.contrib.messages import constants as messages

# =============================================================================
# ОСНОВНЫЕ ПУТИ
# =============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# БЕЗОПАСНОСТЬ И ПРОДАКШН НАСТРОЙКИ
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# Используем переменные окружения для production
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-cmazq1#@(vxigfc$g!vc(f2z+xzg*#m0gum9qqn)ax-r7qfs!f')

# SECURITY WARNING: don't run with debug turned on in production!
# По умолчанию DEBUG выключен в production
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# Разрешенные хосты для production
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,192.168.92.128').split(',')

# CSRF trusted origins для production
CSRF_TRUSTED_ORIGINS = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1').split(',')

# Определяем режим работы (production/development)
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'development')

# =============================================================================
# ПРИЛОЖЕНИЯ
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Мои приложения
    'fefu_lab',
]

# =============================================================================
# ПРОМЕЖУТОЧНОЕ ПО (MIDDLEWARE)
# =============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =============================================================================
# НАСТРОЙКИ URL И ШАБЛОНОВ
# =============================================================================

ROOT_URLCONF = 'web_2025.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Глобальные шаблоны проекта
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Кастомные context processors можно добавить здесь
            ],
        },
    },
]

WSGI_APPLICATION = 'web_2025.wsgi.application'

# =============================================================================
# БАЗА ДАННЫХ
# =============================================================================

# PostgreSQL конфигурация для production
if DJANGO_ENV == 'production':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'fefu_lab_db'),
            'USER': os.environ.get('DB_USER', 'fefu_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    # SQLite для разработки
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# =============================================================================
# ВАЛИДАЦИЯ ПАРОЛЕЙ
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =============================================================================
# МЕЖДУНАРОДНЫЕ НАСТРОЙКИ
# =============================================================================

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Vladivostok'  # Временная зона ДВФУ

USE_I18N = True

USE_TZ = True

# =============================================================================
# СТАТИЧЕСКИЕ ФАЙЛЫ (CSS, JavaScript, Images)
# =============================================================================

STATIC_URL = '/static/'

if DJANGO_ENV == 'production':
    # В production статические файлы собираются в STATIC_ROOT
    STATIC_ROOT = BASE_DIR / 'static'
    # Используем ManifestStaticFilesStorage для версионирования
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
else:
    # В разработке используем STATICFILES_DIRS
    STATICFILES_DIRS = [
        BASE_DIR / "fefu_lab" / "static",
    ]

# =============================================================================
# МЕДИА ФАЙЛЫ (загруженные пользователями)
# =============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# СИСТЕМА АУТЕНТИФИКАЦИИ - НОВЫЕ НАСТРОЙКИ
# =============================================================================

# URL для перенаправления при аутентификации
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Настройки сессий
SESSION_COOKIE_AGE = 1209600  # 2 недели в секундах
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True  # Обновление времени сессии при каждом запросе

# Кастомные бэкенды аутентификации
AUTHENTICATION_BACKENDS = [
    'fefu_lab.backends.EmailBackend',     # Наш кастомный бэкенд для входа по email
    'django.contrib.auth.backends.ModelBackend',  # Стандартный бэкенд Django
]

# =============================================================================
# СООБЩЕНИЯ (MESSAGES)
# =============================================================================

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# =============================================================================
# EMAIL (для обратной связи и восстановления пароля)
# =============================================================================

if DJANGO_ENV == 'production':
    # В production используем SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@fefu-lab.ru')
else:
    # В разработке - вывод email в консоль
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# =============================================================================
# ЛОГИРОВАНИЕ
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'fefu_lab': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# =============================================================================
# ДОПОЛНИТЕЛЬНЫЕ НАСТРОЙКИ DJANGO
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Максимальный размер загружаемых файлов (2.5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440

# Время жизни CSRF токена
CSRF_COOKIE_AGE = 31449600  # 1 год в секундах

# =============================================================================
# НАСТРОЙКИ ДЛЯ PRODUCTION (активируются при DJANGO_ENV=production)
# =============================================================================

if DJANGO_ENV == 'production':
    # Безопасность
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = False  # Если используете HTTPS, установите True
    SESSION_COOKIE_SECURE = False  # True для HTTPS
    CSRF_COOKIE_SECURE = False     # True для HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 год
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Cookies
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # Защита от кликджекинга
    X_FRAME_OPTIONS = 'DENY'
    
    # Content Security Policy (опционально)
    # SECURE_CSP_STYLE_SRC = ["'self'"]
    # SECURE_CSP_SCRIPT_SRC = ["'self'"]
    
    # Логирование для production
    LOGGING['handlers']['file']['level'] = 'WARNING'
    LOGGING['handlers']['console']['level'] = 'WARNING'
    LOGGING['loggers']['django']['level'] = 'WARNING'
    LOGGING['loggers']['fefu_lab']['level'] = 'WARNING'

# =============================================================================
# НАСТРОЙКИ ДЛЯ РАЗРАБОТКИ (активируются при DJANGO_ENV=development)
# =============================================================================

if DJANGO_ENV == 'development' or DEBUG:
    # Для отладки
    INTERNAL_IPS = [
        '127.0.0.1',
        'localhost',
    ]
    
    # Упрощенные настройки для разработки
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    
    # Показывать подробные ошибки
    DEBUG_PROPAGATE_EXCEPTIONS = True
    
    # Отключаем некоторые security настройки для удобства разработки
    if DEBUG:
        SESSION_COOKIE_SECURE = False
        CSRF_COOKIE_SECURE = False
        SECURE_SSL_REDIRECT = False

# =============================================================================
# ДОПОЛНИТЕЛЬНЫЕ ПРОДАКШЕН НАСТРОЙКИ
# =============================================================================

# Настройки кэширования (опционально, для улучшения производительности)
# if DJANGO_ENV == 'production':
#     CACHES = {
#         'default': {
#             'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#             'LOCATION': 'redis://127.0.0.1:6379/1',
#         }
#     }

# Настройки для статических файлов
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Максимальное количество соединений с БД (для PostgreSQL)
if DJANGO_ENV == 'production':
    DATABASES['default']['CONN_MAX_AGE'] = 600  # 10 минут
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,
    }

# Настройки для gunicorn
# Gunicorn будет автоматически использовать эти настройки
WSGI_APPLICATION = 'web_2025.wsgi.application'
ASGI_APPLICATION = None  # Если не используете ASGI

# Запрет индексации поисковыми системами (если нужно)
if DJANGO_ENV == 'production' and not DEBUG:
    # Добавьте в robots.txt: User-agent: *\nDisallow: /
    pass

# =============================================================================
# ФИНАЛЬНАЯ ПРОВЕРКА
# =============================================================================

# Убеждаемся, что в production DEBUG выключен
if DJANGO_ENV == 'production' and DEBUG:
    import warnings
    warnings.warn(
        "DEBUG is True in production environment! "
        "Set DJANGO_DEBUG=False or DJANGO_ENV=production with DEBUG=False",
        RuntimeWarning
    )

# Генерация SECRET_KEY, если он не установлен и мы в production
if DJANGO_ENV == 'production' and SECRET_KEY.startswith('django-insecure-'):
    import warnings
    warnings.warn(
        "Using default insecure SECRET_KEY in production! "
        "Set DJANGO_SECRET_KEY environment variable.",
        RuntimeWarning
    )
