"""
Django settings for web_2025 project.
Generated by 'django-admin startproject' using Django 4.2.
"""

import os
from pathlib import Path
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# БЕЗОПАСНОСТЬ
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cmazq1#@(vxigfc$g!vc(f2z+xzg*#m0gum9qqn)ax-r7qfs!f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.92.128']

# =============================================================================
# ПРИЛОЖЕНИЯ
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Мои приложения
    'fefu_lab',
]

# =============================================================================
# ПРОМЕЖУТОЧНОЕ ПО (MIDDLEWARE)
# =============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =============================================================================
# НАСТРОЙКИ URL И ШАБЛОНОВ
# =============================================================================

ROOT_URLCONF = 'web_2025.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Глобальные шаблоны проекта
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Кастомные context processors можно добавить здесь
            ],
        },
    },
]

WSGI_APPLICATION = 'web_2025.wsgi.application'

# =============================================================================
# БАЗА ДАННЫХ
# =============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# =============================================================================
# ВАЛИДАЦИЯ ПАРОЛЕЙ
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =============================================================================
# МЕЖДУНАРОДНЫЕ НАСТРОЙКИ
# =============================================================================

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Vladivostok'  # Временная зона ДВФУ

USE_I18N = True

USE_TZ = True

# =============================================================================
# СТАТИЧЕСКИЕ ФАЙЛЫ (CSS, JavaScript, Images)
# =============================================================================

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "fefu_lab" / "static",
]

# Для production нужно добавить:
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# =============================================================================
# МЕДИА ФАЙЛЫ (загруженные пользователями)
# =============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# СИСТЕМА АУТЕНТИФИКАЦИИ - НОВЫЕ НАСТРОЙКИ
# =============================================================================

# URL для перенаправления при аутентификации
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Настройки сессий
SESSION_COOKIE_AGE = 1209600  # 2 недели в секундах
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True  # Обновление времени сессии при каждом запросе

# Безопасность cookies (в production установить True)
SESSION_COOKIE_SECURE = False  # True для HTTPS
CSRF_COOKIE_SECURE = False     # True для HTTPS

# Кастомные бэкенды аутентификации
AUTHENTICATION_BACKENDS = [
    'fefu_lab.backends.EmailBackend',     # Наш кастомный бэкенд для входа по email
    'django.contrib.auth.backends.ModelBackend',  # Стандартный бэкенд Django
]

# =============================================================================
# СООБЩЕНИЯ (MESSAGES)
# =============================================================================

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# =============================================================================
# EMAIL (для обратной связи и восстановления пароля)
# =============================================================================

# Для разработки - вывод email в консоль
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Для production:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.yandex.ru'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'noreply@fefu-lab.ru'
# EMAIL_HOST_PASSWORD = 'your-password'

# =============================================================================
# ЛОГИРОВАНИЕ
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'fefu_lab': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# =============================================================================
# ДОПОЛНИТЕЛЬНЫЕ НАСТРОЙКИ DJANGO
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Максимальный размер загружаемых файлов (2.5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440

# Время жизни CSRF токена
CSRF_COOKIE_AGE = 31449600  # 1 год в секундах

# =============================================================================
# НАСТРОЙКИ ДЛЯ РАЗРАБОТКИ
# =============================================================================

if DEBUG:
    # Для отладки
    INTERNAL_IPS = [
        '127.0.0.1',
        'localhost',
    ]
    
    # Упрощенные настройки для разработки
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    
    # Показывать подробные ошибки
    DEBUG_PROPAGATE_EXCEPTIONS = True

# =============================================================================
# НАСТРОЙКИ ДЛЯ PRODUCTION (раскомментировать при развертывании)
# =============================================================================

# if not DEBUG:
#     # Безопасность
#     SECURE_BROWSER_XSS_FILTER = True
#     SECURE_CONTENT_TYPE_NOSNIFF = True
#     SECURE_SSL_REDIRECT = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
#     SECURE_HSTS_SECONDS = 31536000  # 1 year
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True
#     
#     # Статические файлы
#     STATIC_ROOT = BASE_DIR / 'staticfiles'
#     
#     # База данных для production (пример для PostgreSQL)
#     # DATABASES = {
#     #     'default': {
#     #         'ENGINE': 'django.db.backends.postgresql',
#     #         'NAME': 'fefu_lab_db',
#     #         'USER': 'fefu_user',
#     #         'PASSWORD': 'secure_password',
#     #         'HOST': 'localhost',
#     #         'PORT': '5432',
#     #     }
#     # }
